/**
 * Student: Gomolemo Tshenye
 * Student Number: ST10341577
 * Assessment: ICE Task 1 - Student Bursary Claims Management System
 */

import { body, param, validationResult } from 'express-validator';
import { MAX_MONTHLY_HOURS } from '../config/constants.js';

// Request validation is performed before controller logic to reject invalid or client-controlled fields (Express Validator, 2026; OWASP Foundation, 2021).
export const createClaimValidation = [
  body('studentNumber')
    .isString().withMessage('Student Number must be text.')
    .trim().notEmpty().withMessage('Student Number is required.')
    .isLength({ max: 20 }).withMessage('Student Number must not exceed 20 characters.'),
  body('firstName')
    .isString().withMessage('First Name must be text.')
    .trim().notEmpty().withMessage('First Name is required.')
    .isLength({ max: 50 }).withMessage('First Name must not exceed 50 characters.'),
  body('surname')
    .isString().withMessage('Surname must be text.')
    .trim().notEmpty().withMessage('Surname is required.')
    .isLength({ max: 50 }).withMessage('Surname must not exceed 50 characters.'),
  body('hoursWorked')
    .isFloat({ gt: 0, max: MAX_MONTHLY_HOURS })
    .withMessage(`Hours Worked must be greater than 0 and no more than ${MAX_MONTHLY_HOURS}.`),
  body('hourlyRate').not().exists().withMessage('Hourly Rate is assigned by the server and must not be supplied.'),
  body('totalClaimAmount').not().exists().withMessage('Total Claim Amount is calculated by the server and must not be supplied.'),
  body('dateSubmitted').not().exists().withMessage('Date Submitted is generated by the server and must not be supplied.'),
  body('status').not().exists().withMessage('Status is assigned by the server and must not be supplied.')
];

export const studentNumberValidation = [
  param('studentNumber')
    .trim().notEmpty().withMessage('Student Number is required.')
    .isLength({ max: 20 }).withMessage('Student Number must not exceed 20 characters.')
];

export const mongoIdValidation = [
  param('claimId').isMongoId().withMessage('Claim ID must be a valid MongoDB ObjectId.')
];

export function handleValidationErrors(req, res, next) {
  const errors = validationResult(req);
  if (errors.isEmpty()) return next();
  return res.status(400).json({
    status: 400,
    message: 'Validation failed.',
    errors: errors.array().map(({ path, msg }) => ({ field: path, message: msg }))
  });
}

/**
 * COMMENT REFERENCE LIST
 * 1. Express Validator (2026) 'express-validator documentation'. Available at: https://express-validator.github.io/docs/ (Accessed: 25 September 2026).
 * 2. OWASP Foundation (2021) 'Input Validation Cheat Sheet'. Available at: https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html (Accessed: 25 September 2026).
 */
